language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
  - chmod +x gradlew

script:
  - ./gradlew testDebugUnitTest coveralls